"use client";

import { useEffect, useState } from "react";

const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]||c));
const PAGE_URL=()=>window.location.href.split("#")[0];
function reportHtml(){
 const title=document.querySelector("h1")?.textContent?.trim()||"Engineering Calculation";
 const subtitle=document.querySelector(".subtitle")?.textContent?.trim()||"";
 const fields=[...document.querySelectorAll("label")].map(el=>{const input=el.querySelector("input,select") as HTMLInputElement|HTMLSelectElement|null;if(!input)return null;const label=(el.querySelector("span")?.textContent||el.childNodes[0]?.textContent||"").trim();return label?[label,input.value]:null}).filter(Boolean) as string[][];
 const metrics=[...document.querySelectorAll(".metric,.model-strip>div")].map(el=>[(el.querySelector("span")?.textContent||"").trim(),(el.querySelector("strong")?.textContent||"").trim()]).filter(x=>x[0]);
 const resultCard=document.querySelector(".results-card");
 const resultHeading=resultCard?.querySelector(".eyebrow")?.textContent?.trim()||"";
 const resultMain=resultCard?.querySelector(".result-main")?.textContent?.trim().replace(/\s+/g," ")||"";
 const tables=[...document.querySelectorAll("table")].map(t=>t.outerHTML).join("");
 const visuals=[...document.querySelectorAll("svg")].filter(svg=>!svg.closest(".sidebar")&&!svg.closest("button")).map(svg=>`<div class="visual">${svg.outerHTML}</div>`).join("");
 const rows=(arr:string[][])=>arr.map(r=>`<tr>${r.map((x,i)=>`<${i?"td":"th"}>${esc(x)}</${i?"td":"th"}>`).join("")}</tr>`).join("");
 const url=PAGE_URL();
 return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4;margin:18mm 14mm 18mm}*{box-sizing:border-box}body{font:10.5px Arial;color:#24364d;margin:0}header{display:flex;align-items:center;gap:12px;border-bottom:3px solid #365b91;padding-bottom:10px;margin-bottom:16px}.logo{width:46px;height:46px}.headtext{flex:1}h1{font-size:22px;margin:0;color:#263d5e}h2{font-size:13px;color:#365b91;margin:18px 0 7px}.sub,.url,.date{color:#718096}.url{font-size:9px;margin-top:4px}.date{text-align:right;white-space:nowrap}.recommend{border:2px solid #365b91;background:#eef4fb;padding:10px 12px;margin:10px 0 16px}.recommend small{display:block;letter-spacing:1px;color:#365b91;font-weight:bold}.recommend strong{display:block;font-size:20px;color:#17375e;margin-top:4px}table{width:100%;border-collapse:collapse;margin:7px 0 15px;font-size:9.5px;page-break-inside:auto}thead{display:table-header-group}tr{page-break-inside:avoid}th{background:#dbe8f5;color:#263d5e;text-align:left;font-weight:700}th,td{border:1px solid #9aa9ba;padding:5px 6px}tr:nth-child(even) td{background:#f7f9fb}.visual{border:1px solid #ccd6e2;border-radius:6px;padding:10px;margin:8px 0 14px;page-break-inside:avoid;text-align:center}.visual svg{max-width:100%;height:auto;max-height:310px}.note{margin-top:18px;padding:9px;background:#eef7f2;border-left:3px solid #28755a;color:#365b50}footer{margin-top:16px;padding-top:7px;border-top:1px solid #ccd6e2;font-size:8.5px;color:#718096}.download-btn,.report-export-tools,button{display:none!important}</style></head><body><header><img class="logo" src="${location.origin}/brand-mark.svg"/><div class="headtext"><h1>${esc(title)}</h1><div class="sub">${esc(subtitle)}</div><div class="url">${esc(url)}</div></div><div class="date">${new Date().toLocaleDateString("en-AU")}</div></header>${resultHeading&&resultMain?`<div class="recommend"><small>${esc(resultHeading)}</small><strong>${esc(resultMain)}</strong></div>`:""}${fields.length?`<h2>Design inputs</h2><table>${rows(fields)}</table>`:""}${metrics.length?`<h2>Results summary</h2><table>${rows(metrics)}</table>`:""}${visuals?`<h2>Design schematic</h2>${visuals}`:""}${tables?`<h2>Calculation tables</h2>${tables}`:""}<div class="note">Engineering Tools calculation report. Verify inputs, assumptions, governing standards and site-specific design requirements before issue.</div><footer>${esc(url)}</footer></body></html>`;
}
function exportPdf(){const w=window.open("","_blank","width=900,height=1100");if(!w)return;w.document.write(reportHtml());w.document.close();try{w.history.replaceState({},"",PAGE_URL())}catch{}w.focus();setTimeout(()=>w.print(),450)}
function exportExcel(){const html=reportHtml();const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff",html],{type:"application/vnd.ms-excel;charset=utf-8"}));a.download=`${(document.querySelector("h1")?.textContent||"engineering-calculation").toLowerCase().replace(/[^a-z0-9]+/g,"-")}.xls`;a.click();URL.revokeObjectURL(a.href)}
export default function ReportExportTools(){const [show,setShow]=useState(false);useEffect(()=>{const check=()=>{const csv=[...document.querySelectorAll("button")].filter(b=>/export.*csv/i.test(b.textContent||"")) as HTMLElement[];csv.forEach(b=>b.style.display="none");setShow(csv.length>0)};check();const o=new MutationObserver(check);o.observe(document.body,{subtree:true,childList:true});return()=>o.disconnect()},[]);if(!show)return null;return <div className="report-export-tools"><button onClick={exportPdf}>↓ Export PDF</button><button onClick={exportExcel}>↓ Export Excel</button></div>}
